### ISSUE TITLE
support for Angular 2/4?

### ISSUE THREAD

**Issue by jamesleegovtech** [ghiscoding/angular-markdown-editor#16] opened 2017-08-15 08:01 UTC
does this have support for the new Angular 4? or even Angular 2?

I'm working on a project with Angular 4 and would really love to add this module to my project.

**Comment by ghiscoding** [comment] 2017-08-15 13:01
I did not start working with Angular 2+ yet, so I didn't do any conversion yet but I certainly welcome PR if you want to help port it over.

**Comment by ghiscoding** [comment] 2018-09-21 23:03
Duplicate of #4 
Follow the discussion in #4... it's coming

**Closed by ghiscoding** 2018-09-21 23:03 UTC
Labels: help wanted
