### ISSUE TITLE
Scrolling after press 'Enter' key 

### ISSUE THREAD

**Issue by TinkyWinky7879800** [ghiscoding/angular-markdown-editor#34] opened 2022-08-24 09:07 UTC
* **Library Version:**
2.0.2

**Current behavior:**
It can be reproduced on your demo page, put cursor in middle of any text and press 'Enter', then scroll will move edited row to the top or bottom of text area.

**Expected/desired behavior:**
Not to change scroll after pressing 'Enter' key.

**Comment by ghiscoding** [comment] 2022-08-25 04:02
I'm on Windows and it doesn't seem to be doing that at all on my side, and even if there's a problem it's probably in the `bootstrap-markdown` editor lib (so outside of this lib). I also don't have much bandwidth to spend on this lib anymore, I tried upgrading to latest Angular version and the upgrade just fails and I really have no time to redo it from scratch. Sorry I can't provide more help at this point

**Comment by ghiscoding** [comment] 2022-09-12 20:48
closing since I cannot reproduce and even if there was a problem then it would have to be in the `bootstrap-markdown` editor library which is outside of current lib.

**Closed by ghiscoding** 2022-09-12 20:48 UTC
Labels: cannot reproduce
